title: Blog GitHub Pages

theme: minima

author: Geuluk
email: geuluk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In questo blog appuntiamo tutti i passaggi per
  creare un semplice sito web su GitHub Pages.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: @geuluk # DO NOT include the @ character, or else the build will fail!
github_username:  @geuluk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
